version: '3.4'

services:
    web:
        build:
           context: .
           dockerfile: Dockerfile
        environment:
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - SUGAR=${SUGAR}
          - SPICE=${SPICE}
        volumes:
           - $PWD/portal:/var/www/html
           - $PWD:/glycoTree
        ports:
           - 10989:80
        links:
           - mysql
    mysql:
        image: mysql
        restart: always
        environment:
           - MYSQL_SERVER_NAME=mysql
           - MYSQL_DATABASE=glycotree
           - MYSQL_USER=gt_user
           - MYSQL_PASSWORD=${MYSQL_PASSWORD}
           - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
           - SUGAR=${SUGAR}
           - SPICE=${SPICE}
        volumes:
           - $PWD/SQL/server:/docker-entrypoint-initdb.d
           - $PWD:/glycoTree
