#!/bin/bash
# Usage: ./populateDB -u <user> -d <mysql_bin_directory>  -a <sandbox api server>
#  !!! The examples below work ONLY for mysql operating within MAMP !!!
# Example:
#  ./populateDB.sh -u gt_user -d /Applications/MAMP/Library/bin/ -a https://glygen.ccrc.uga.edu/sandbox/api
# Example:
# ./populateDB.sh -u gt_user -d /Applications/MAMP/Library/bin/ -a localhost:8080/api
#  This script populates the glycotree DB using the mysqlimport command
#  For security reasons, YOU must supply the 
#    DB user_name and directory containing mysqlimport
#    User will be prompted for the MYSQL password

# The commands in this script assume it is called from glycotree/SQL/
#  Thus, files specifying the model are in the directory ../model/

start=$(date)
echo $start
COUNT=0

# initiate (global) canonical_residues.csv with N_canonical_residues.csv
cp ../model/N_canonical_residues.csv ./canonical_residues.csv
# append canonical_residues.csv with O_canonical_residues.csv (remove header line)
awk 'NR > 1 {print($0);}' ../model/O_canonical_residues.csv >> ./canonical_residues.csv
cp ../model/enzymes.csv ./enzymes.csv
cp ../model/enzyme_mappings.csv ./enzyme_mappings.csv
cp ../model/rules.tsv ./rules.tsv
cp ../model/rule_data.tsv ./rule_data.tsv
	
# glycotree/SQL/compositions.csv is generated by glycotree/build_N-tree.sh
# glycotree/SQL/correlation.csv is generated by glycotree/build_N-tree.sh

user="gt_user"
export MYSQL_PWD="$MYSQL_PASSWORD"

echo
echo "populating SQL Tables"
echo

set -x
MYSQL="mysql -u $user -h localhost -P 3306 --local-infile=1 -v -v -v glycotree"

echo "SET GLOBAL local_infile=1;" | mysql -uroot -h localhost -P 3306 -v -v -v

echo "show tables" | $MYSQL

# echo "glytoucan_ac,residue_name,residue_id,name,anomer,absolute,ring,parent_id,site,form_name,glycoct_index,notes" > compositions.tmp
# fgrep -v glytoucan_ac compositions.csv >> compositions.tmp
# mv -f compositions.tmp compositions.csv
for f in canonical_residues.csv compositions.csv correlation.csv enzyme_mappings.csv enzymes.csv bitSet.tsv curators.tsv rule_data.tsv rules.tsv; do
  ( ./loadtsv.sh ./$f | $MYSQL ) || exit 1
done

mysqldump -u $user --no-tablespaces glycotree > ./server/glycotree.sql
